@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

interface ActionCommandListener << interface >> {
  + eventOccurred(String): void
}
enum ActionCommandsEnum << enumeration >> {
  + ActionCommandsEnum(): 
  + values(): ActionCommandsEnum[]
  + valueOf(String): ActionCommandsEnum
}
class ActiveBasePanel {
  # ActiveBasePanel(): 
  # activateComps(): void
}
class AddBookCommand {
  + AddBookCommand(String, String, String, String, double): 
  + execute(): boolean
  + undo(): boolean
  # createMessage(): void
  + canExecute(): boolean
  + redo(): boolean
}
class AddBookFormPanel {
  + AddBookFormPanel(): 
  # initComps(): void
  - setupVrstaModel(): void
  # layoutComps(): void
   autor: String
   naziv: String
   cijena: double
   isbn: String
   vrsta: String
}
class AddBookRightPanel {
  + AddBookRightPanel(): 
  # layoutComps(): void
  # initComps(): void
  # activateComps(): void
   selectedBook: Knjiga
   addBookWindowListener: ActionCommandListener
}
class AddBookWindow {
  + AddBookWindow(): 
  # initComps(): void
  # activateComps(): void
  # layoutComps(): void
  - izvrsiUnos(): void
}
class AddressMissingDecorator {
  + AddressMissingDecorator(ReturnMessage): 
   message: String
}
class App {
  + App(): 
  + main(String[]): void
}
class BaseCommand {
  + BaseCommand(): 
  # createMessage(): void
}
class BaseDialog {
  + BaseDialog(JDialog, String, boolean): 
  + BaseDialog(JFrame, String, boolean): 
  - setup(): void
  - animationFadeIn(): void
  # initComps(): void
  # activateComps(): void
  # animationFadeOut(): void
  # layoutComps(): void
   x: int
   opacity: float
   y: int
}
class BaseFrame {
  # BaseFrame(String): 
  # animationFadeIn(): void
  # initComps(): void
  # animationFadeOut(): void
  # activateComps(): void
  # layoutComps(): void
   x: int
   opacity: float
   y: int
}
class BasePanel {
  # BasePanel(): 
  # layoutComps(): void
  # initComps(): void
}
class BasicReturnMessage {
  + BasicReturnMessage(String): 
  - message: String
   message: String
}
class BookAlreadyBorrowedDecorator {
  + BookAlreadyBorrowedDecorator(ReturnMessage): 
   message: String
}
class BookDAO {
  - BookDAO(): 
  + delete(String): boolean
  + insert(Knjiga): boolean
  + updateBorrowStatus(Knjiga, Integer): boolean
   all: List<Knjiga>
   instance: BookDAO
}
class BookNotBorrowedDecorator {
  + BookNotBorrowedDecorator(ReturnMessage): 
   message: String
}
class BookNotSelectedDecorator {
  + BookNotSelectedDecorator(ReturnMessage): 
   message: String
}
class BorrowBookCommand {
  + BorrowBookCommand(Knjiga, Customer, int): 
  + undo(): boolean
  # createMessage(): void
  + execute(): boolean
  + canExecute(): boolean
  + redo(): boolean
}
class BuyBookCommand {
  + BuyBookCommand(Knjiga): 
  + undo(): boolean
  + execute(): boolean
  + canExecute(): boolean
  + redo(): boolean
  # createMessage(): void
}
class BuyBookWindow {
  + BuyBookWindow(JFrame): 
  # layoutComps(): void
  - saleProcedure(): void
  # initComps(): void
  - updatePriceLabel(): void
  # activateComps(): void
}
class CardPayment {
  + CardPayment(): 
  + processPayment(double): void
}
class CashPayment {
  + CashPayment(): 
  + processPayment(double): void
}
class CityMissingDecorator {
  + CityMissingDecorator(ReturnMessage): 
   message: String
}
interface Command << interface >> {
  + canExecute(): boolean
  + undo(): boolean
  + execute(): boolean
  + redo(): boolean
}
class CommandManager {
  - CommandManager(): 
  + redo(): boolean
  + executeCommand(Command): boolean
  + undo(): boolean
   instance: CommandManagerInterface
}
interface CommandManagerInterface << interface >> {
  + executeCommand(Command): boolean
  + redo(): boolean
  + undo(): boolean
}
class ConjoinedPanel {
  + ConjoinedPanel(): 
  # layoutComps(): void
  + actionPerformed(ActionEvent): void
  # initComps(): void
  # activateComps(): void
   conjoinedPanelListener: ActionCommandListener
   userViewPanelListener: ViewPanelListener<Customer>
}
class ConjoinedRegisterLibrarianPanel {
  + ConjoinedRegisterLibrarianPanel(): 
  # initComps(): void
  # layoutComps(): void
}
entity ConnectionInfo << record >> {
  + ConnectionInfo(): 
}
class CryptoPayment {
  + CryptoPayment(): 
  + processPayment(double): void
}
class Customer {
  + Customer(String, String, int, String, String): 
  - posudeneKnjige: List<Knjiga>
  + toString(): String
  + vratiKnjigu(Knjiga): void
  + posudiKnjigu(Knjiga): void
   posudeneKnjige: List<Knjiga>
}
class CustomerDAO {
  - CustomerDAO(): 
  + insert(Customer): boolean
  + delete(int): boolean
   all: List<Customer>
   instance: CustomerDAO
}
class CustomerFactory {
  - CustomerFactory(): 
  - instance: CustomerFactory
  + createUser(String, String, int, String, String): User
   instance: CustomerFactory
}
class CustomerHasBorrowedBooksDecorator {
  + CustomerHasBorrowedBooksDecorator(ReturnMessage): 
   message: String
}
class CustomerNotSelected {
  + CustomerNotSelected(ReturnMessage): 
   message: String
}
class CustomerNotSelectedDecorator {
  + CustomerNotSelectedDecorator(ReturnMessage): 
   message: String
}
class CustomerViewPanel {
  + CustomerViewPanel(int, int): 
  + CustomerViewPanel(): 
}
interface DBConnectionManagerInterface << interface >> {
  + connect(): boolean
  + disconnect(): void
   connection: Connection
   connectionAlive: boolean
}
class DamageFeeDecorator {
  + DamageFeeDecorator(ReturnMessage): 
   message: String
}
class DatabaseConnectionManager {
  + DatabaseConnectionManager(): 
  - connection: Connection
  + disconnect(): void
  + connect(): boolean
  - returnNotConnectedMsg(): void
   connection: Connection
   instance: DBConnectionManagerInterface
   connectionAlive: boolean
}
class DeleteBookCommand {
  + DeleteBookCommand(Knjiga): 
  + undo(): boolean
  + canExecute(): boolean
  # createMessage(): void
  + execute(): boolean
  + redo(): boolean
}
class DeleteCustomerCommand {
  + DeleteCustomerCommand(Customer): 
  + canExecute(): boolean
  + undo(): boolean
  + redo(): boolean
  + execute(): boolean
  # createMessage(): void
}
class DeleteLibrarianCommand {
  + DeleteLibrarianCommand(Librarian): 
  + redo(): boolean
  + execute(): boolean
  # createMessage(): void
  + canExecute(): boolean
  + undo(): boolean
}
class EffectUtils {
  + EffectUtils(): 
  + shakeWindow(JFrame): void
}
class EmptyAuthorDecorator {
  + EmptyAuthorDecorator(ReturnMessage): 
   message: String
}
class EmptyCijenaDecorator {
  + EmptyCijenaDecorator(ReturnMessage): 
   message: String
}
class EmptyISBNdecorator {
  + EmptyISBNdecorator(ReturnMessage): 
   message: String
}
class EmptyNazivDecorator {
  + EmptyNazivDecorator(ReturnMessage): 
   message: String
}
class EmptyVrstaDecorator {
  + EmptyVrstaDecorator(ReturnMessage): 
   message: String
}
enum FilePathEnum << enumeration >> {
  + FilePathEnum(): 
  + values(): FilePathEnum[]
  + valueOf(String): FilePathEnum
}
interface FilterInterface << interface >> {
  + getFilteredBooks(String): List<Knjiga>
  + getFilteredCustomers(String): List<Customer>
  + getFilteredLibrarians(String): List<Librarian>
   librarianFilter: String
   bookFilter: String
   customerFilter: String
}
class Holder {
  + Holder(): 
}
class Holder {
  + Holder(): 
}
class Holder {
  + Holder(): 
}
class Holder {
  + Holder(): 
}
class Holder {
  + Holder(): 
}
class Holder {
  + Holder(): 
}
class Holder {
  + Holder(): 
}
interface IntBookDAO << interface >> {
  + updateBorrowStatus(Knjiga, Integer): boolean
  + insert(Knjiga): boolean
  + delete(String): boolean
   all: List<Knjiga>
}
interface IntCustomerDAO << interface >> {
  + delete(int): boolean
  + insert(Customer): boolean
   all: List<Customer>
}
interface IntLibrarianDAO << interface >> {
  + delete(int): boolean
  + update(Librarian): boolean
  + insert(Librarian): boolean
   all: List<Librarian>
}
class InvalidAgeDecorator {
  + InvalidAgeDecorator(ReturnMessage): 
   message: String
}
class Knjiga {
  + Knjiga(String, String, String, String, double): 
  - autor: String
  - isbn: String
  - vrstaDjela: String
  - nazivDjela: String
  - danaPosudbe: int
  - tmpCustomerId: int
  - posudjena: boolean
  - cijena: double
  - posudioCustomer: Customer
  + vrati(): void
  - customerInfo(): String
  + toString(): String
  + posudi(int): void
  - dostupnost(): String
   danaPosudbe: int
   tmpCustomerId: int
   cijena: double
   nazivDjela: String
   posudjena: boolean
   posudioCustomer: Customer
   autor: String
   vrstaDjela: String
   isbn: String
}
class KnjigeViewPanel {
  + KnjigeViewPanel(): 
  + KnjigeViewPanel(FilePathEnum, int, int): 
  + emptyModel(): void
  + populateBorrowedBooksList(Customer): void
}
class LastnameMissingDecorator {
  + LastnameMissingDecorator(ReturnMessage): 
   message: String
}
class LateFeeDecorator {
  + LateFeeDecorator(ReturnMessage): 
   message: String
}
class Librarian {
  + Librarian(String, String, String, String, int, String, String): 
  + Librarian(String, String, String, String, int, String, String, boolean): 
  - isAdmin: boolean
  - username: String
  - password: String
  + toString(): String
   isAdmin: boolean
   password: String
   username: String
}
class LibrarianDAO {
  - LibrarianDAO(): 
  + update(Librarian): boolean
  + insert(Librarian): boolean
  + delete(int): boolean
   all: List<Librarian>
   instance: LibrarianDAO
}
class LibrarianFactory {
  - LibrarianFactory(): 
  - instance: LibrarianFactory
  + setCredentials(String, String): void
  + createUser(String, String, int, String, String): User
   instance: LibrarianFactory
}
class LibrarianLoggedInDecorator {
  + LibrarianLoggedInDecorator(ReturnMessage): 
   message: String
}
class LibrarianManagementPanel {
  + LibrarianManagementPanel(): 
  - listener: ActionCommandListener
  # layoutComps(): void
  # activateComps(): void
  # initComps(): void
  + actionPerformed(ActionEvent): void
   listener: ActionCommandListener
}
class LibrarianManagementWindow {
  + LibrarianManagementWindow(JFrame): 
  # layoutComps(): void
  # activateComps(): void
  # initComps(): void
  - deleteButtonProcedure(): void
}
class LibrarianNotSelectedDecorator {
  + LibrarianNotSelectedDecorator(ReturnMessage): 
   message: String
}
class LibrarianViewPanel {
  + LibrarianViewPanel(): 
  + LibrarianViewPanel(int, int): 
}
class LibraryManager {
  - LibraryManager(): 
  - bookFilter: String
  - customerFilter: String
  - knjige: List<Knjiga>
  - customers: List<Customer>
  - librarians: List<Librarian>
  - librarianFilter: String
  + returnBook(Knjiga): boolean
  - relinkBooks2Customers(): void
  + removeObserver(Observer): void
  + getFilteredCustomers(String): List<Customer>
  + removeBook(Knjiga): boolean
  + deleteCustomer(Customer): boolean
  + addObserver(Observer): void
  + notifyObservers(): void
  + addCustomer(Customer): boolean
  + deleteLibrarian(Librarian): boolean
  + getFilteredBooks(String): List<Knjiga>
  + getFilteredLibrarians(String): List<Librarian>
  + addLibrarian(Librarian): boolean
  + borrowBook(Knjiga, Customer, int): boolean
  + addBook(Knjiga): boolean
   librarianFilter: String
   instance: LibraryManagerInterface
   bookFilter: String
   customerFilter: String
   librarians: List<Librarian>
   knjige: List<Knjiga>
   customers: List<Customer>
}
interface LibraryManagerInterface << interface >> {
  + addLibrarian(Librarian): boolean
  + deleteCustomer(Customer): boolean
  + borrowBook(Knjiga, Customer, int): boolean
  + addBook(Knjiga): boolean
  + addCustomer(Customer): boolean
  + returnBook(Knjiga): boolean
  + removeBook(Knjiga): boolean
  + deleteLibrarian(Librarian): boolean
   customers: List<Customer>
   knjige: List<Knjiga>
   librarians: List<Librarian>
}
class LogInWindow {
  + LogInWindow(): 
  # layoutComps(): void
  - checkLogInCredentials(String, String): boolean
  # initComps(): void
  # activateComps(): void
}
class MainFrame {
  + MainFrame(): 
  # layoutComps(): void
  # activateComps(): void
  # initComps(): void
  - handleLogout(): void
}
class MainFrameFormPanel {
  + MainFrameFormPanel(): 
  - formPanelListener: ActionCommandListener
  # activateComps(): void
  # layoutComps(): void
  + actionPerformed(ActionEvent): void
  # initComps(): void
   customer: Customer
   brojDana: int
   formPanelListener: ActionCommandListener
}
class MenuBar {
  + MenuBar(): 
  - menuListener: ActionCommandListener
  - layoutComps(): void
  - activateComps(): void
  - initComps(): void
  - updateConnectionStatus(): void
   menuListener: ActionCommandListener
}
class MessageDecorator {
  + MessageDecorator(ReturnMessage): 
}
class NameMissingDecorator {
  + NameMissingDecorator(ReturnMessage): 
   message: String
}
interface Observable << interface >> {
  + addObserver(Observer): void
  + removeObserver(Observer): void
  + notifyObservers(): void
}
interface Observer << interface >> {
  + update(): void
}
class PasswordMissingDecorator {
  + PasswordMissingDecorator(ReturnMessage): 
   message: String
}
interface PaymentStrategy << interface >> {
  + processPayment(double): void
}
enum PaymentStrategyEnum << enumeration >> {
  + PaymentStrategyEnum(): 
  + values(): PaymentStrategyEnum[]
  + valueOf(String): PaymentStrategyEnum
}
class RegisterCustomerBottomPanel {
  ~ RegisterCustomerBottomPanel(): 
  # activateComps(): void
  # initComps(): void
  # layoutComps(): void
  + actionPerformed(ActionEvent): void
   actionListener: ActionCommandListener
}
class RegisterCustomerCommand {
  + RegisterCustomerCommand(String, String, int, String, String): 
  - sameNameCustomer(): boolean
  + undo(): boolean
  + execute(): boolean
  # createMessage(): void
  + canExecute(): boolean
  + redo(): boolean
}
class RegisterCustomerPanel {
  + RegisterCustomerPanel(): 
  # layoutComps(): void
  # activateComps(): void
  + actionPerformed(ActionEvent): void
  # initComps(): void
   dob: int
   grad: String
   prezime: String
   ime: String
   actionCommandListener: ActionCommandListener
   adresa: String
}
class RegisterCustomerWindow {
  + RegisterCustomerWindow(): 
  - register(): void
  # layoutComps(): void
  # initComps(): void
  # activateComps(): void
}
class RegisterLibLeftPanel {
  + RegisterLibLeftPanel(): 
  - libLeftPanelListener: ActionCommandListener
  # activateComps(): void
  + actionPerformed(ActionEvent): void
  # initComps(): void
  # layoutComps(): void
   prezime: String
   password: String
   dob: int
   grad: String
   username: String
   ime: String
   libLeftPanelListener: ActionCommandListener
   adresa: String
}
class RegisterLibrarianCommand {
  + RegisterLibrarianCommand(String, String, String, String, int, String, String): 
  + redo(): boolean
  + undo(): boolean
  + canExecute(): boolean
  + execute(): boolean
  - exists(): boolean
  # createMessage(): void
}
class RegisterLibrarianWindow {
  + RegisterLibrarianWindow(JFrame): 
  + RegisterLibrarianWindow(JDialog): 
  # activateComps(): void
  - izvrsiUnos(): void
  # layoutComps(): void
  # initComps(): void
  - setupWindow(): void
}
class ReturnBookCommand {
  + ReturnBookCommand(Knjiga, boolean, boolean): 
  + canExecute(): boolean
  + execute(): boolean
  + undo(): boolean
  + redo(): boolean
  # createMessage(): void
}
interface ReturnBookFormListener << interface >> {
  + returnBookFormEventOccured(String, boolean, boolean): void
}
class ReturnBookFormPanel {
  + ReturnBookFormPanel(): 
  - stetaCheckBox: JCheckBox
  - returnBookFormListener: ReturnBookFormListener
  - kasnjenjeCheckBox: JCheckBox
  # initComps(): void
  # activateComps(): void
  + actionPerformed(ActionEvent): void
  # layoutComps(): void
   kasnjenjeCheckBox: JCheckBox
   stetaCheckBox: JCheckBox
   returnBookFormListener: ReturnBookFormListener
}
class ReturnBookWindow {
  + ReturnBookWindow(): 
  # initComps(): void
  # layoutComps(): void
  # activateComps(): void
}
interface ReturnMessage << interface >> {
   message: String
}
class SearchField {
  + SearchField(FilePathEnum, int): 
  + SearchField(FilePathEnum): 
  - filter(String): void
  - setup(FilePathEnum): void
  - activate(): void
}
class SessionManager {
  - SessionManager(): 
  - loggedInUser: Librarian
  + logout(): void
  + authenticate(String, String): boolean
   loggedInUser: Librarian
   currentUserAdmin: boolean
   instance: SessionManager
}
interface SessionManagerInterface << interface >> {
  + authenticate(String, String): boolean
  + logout(): void
   currentUserAdmin: boolean
   loggedInUser: User
}
class ShortcuttableDialog {
  + ShortcuttableDialog(JDialog, String, boolean): 
  + ShortcuttableDialog(JFrame, String, boolean): 
  - setupGlobalShortcuts(): void
}
class ShortcuttableFrame {
  + ShortcuttableFrame(String): 
  - setupGlobalShortcuts(): void
}
class ToolBar {
  + ToolBar(): 
  - toolBarListener: ActionCommandListener
  + actionPerformed(ActionEvent): void
  # initComps(): void
  # activateComps(): void
  # layoutComps(): void
  - checkAdminRights(): void
   toolBarListener: ActionCommandListener
}
class User {
  # User(String, String, int, String, String): 
  # grad: String
  # ime: String
  # id: int
  # dob: int
  # prezime: String
  # adresaStanovanja: String
   dob: int
   grad: String
   prezime: String
   ime: String
   adresaStanovanja: String
   id: int
}
interface UserFactory << interface >> {
  + createUser(String, String, int, String, String): User
}
class UsernameMissingDecorator {
  + UsernameMissingDecorator(ReturnMessage): 
   message: String
}
class ViewPanel<E> {
  # ViewPanel(FilePathEnum, int, int): 
  # ViewPanel(FilePathEnum): 
  # listModel: DefaultListModel<E>
  # list: JList<E>
  - updateModel(List<E>): void
  - setupPanel(FilePathEnum, int, int): void
  + update(): void
  # initComps(): void
  - fetchLatestData(): List<E>
  # layoutComps(): void
   list: JList<E>
   listModel: DefaultListModel<E>
   viewPanelListener: ViewPanelListener<E>
   selectedValue: E
}
interface ViewPanelListener<E> << interface >> {
  + eventOccurred(E): void
}
enum VrsteDjelaEnum << enumeration >> {
  + VrsteDjelaEnum(): 
  + values(): VrsteDjelaEnum[]
  + valueOf(String): VrsteDjelaEnum
}

ActiveBasePanel                    -[#000082,plain]-^  BasePanel                         
AddBookCommand                     -[#000082,plain]-^  BaseCommand                       
AddBookCommand                     -[#595959,dashed]->  BasicReturnMessage                : "«create»"
AddBookCommand                     -[#008200,dashed]-^  Command                           
AddBookCommand                     -[#595959,dashed]->  EmptyAuthorDecorator              : "«create»"
AddBookCommand                     -[#595959,dashed]->  EmptyCijenaDecorator              : "«create»"
AddBookCommand                     -[#595959,dashed]->  EmptyISBNdecorator                : "«create»"
AddBookCommand                     -[#595959,dashed]->  EmptyNazivDecorator               : "«create»"
AddBookCommand                     -[#595959,dashed]->  EmptyVrstaDecorator               : "«create»"
AddBookCommand                    "1" *-[#595959,plain]-> "newlyCreatedBook\n1" Knjiga                            
AddBookCommand                     -[#595959,dashed]->  Knjiga                            : "«create»"
AddBookCommand                    "1" *-[#595959,plain]-> "libraryManager\n1" LibraryManagerInterface           
AddBookFormPanel                   -[#000082,plain]-^  BasePanel                         
AddBookRightPanel                 "1" *-[#595959,plain]-> "listener\n1" ActionCommandListener             
AddBookRightPanel                  -[#000082,plain]-^  ActiveBasePanel                   
AddBookRightPanel                 "1" *-[#595959,plain]-> "knjigeViewPanel\n1" KnjigeViewPanel                   
AddBookRightPanel                  -[#595959,dashed]->  KnjigeViewPanel                   : "«create»"
AddBookWindow                      -[#595959,dashed]->  AddBookCommand                    : "«create»"
AddBookWindow                      -[#595959,dashed]->  AddBookFormPanel                  : "«create»"
AddBookWindow                     "1" *-[#595959,plain]-> "addBookFormPanel\n1" AddBookFormPanel                  
AddBookWindow                      -[#595959,dashed]->  AddBookRightPanel                 : "«create»"
AddBookWindow                     "1" *-[#595959,plain]-> "addBookRightPanel\n1" AddBookRightPanel                 
AddBookWindow                      -[#595959,dashed]->  DeleteBookCommand                 : "«create»"
AddBookWindow                      -[#595959,dashed]->  MainFrame                         : "«create»"
AddBookWindow                      -[#000082,plain]-^  ShortcuttableFrame                
AddressMissingDecorator            -[#000082,plain]-^  MessageDecorator                  
App                                -[#595959,dashed]->  LogInWindow                       : "«create»"
BasicReturnMessage                 -[#008200,dashed]-^  ReturnMessage                     
BookAlreadyBorrowedDecorator       -[#000082,plain]-^  MessageDecorator                  
BookDAO                            -[#008200,dashed]-^  IntBookDAO                        
BookDAO                            -[#595959,dashed]->  Knjiga                            : "«create»"
BookNotBorrowedDecorator           -[#000082,plain]-^  MessageDecorator                  
BookNotSelectedDecorator           -[#000082,plain]-^  MessageDecorator                  
BorrowBookCommand                  -[#000082,plain]-^  BaseCommand                       
BorrowBookCommand                  -[#595959,dashed]->  BasicReturnMessage                : "«create»"
BorrowBookCommand                  -[#595959,dashed]->  BookAlreadyBorrowedDecorator      : "«create»"
BorrowBookCommand                  -[#595959,dashed]->  BookNotSelectedDecorator          : "«create»"
BorrowBookCommand                  -[#008200,dashed]-^  Command                           
BorrowBookCommand                 "1" *-[#595959,plain]-> "customer\n1" Customer                          
BorrowBookCommand                  -[#595959,dashed]->  CustomerNotSelectedDecorator      : "«create»"
BorrowBookCommand                 "1" *-[#595959,plain]-> "selectedBook\n1" Knjiga                            
BorrowBookCommand                 "1" *-[#595959,plain]-> "libraryManager\n1" LibraryManagerInterface           
BuyBookCommand                     -[#000082,plain]-^  BaseCommand                       
BuyBookCommand                     -[#595959,dashed]->  BasicReturnMessage                : "«create»"
BuyBookCommand                     -[#595959,dashed]->  BookAlreadyBorrowedDecorator      : "«create»"
BuyBookCommand                     -[#595959,dashed]->  BookNotSelectedDecorator          : "«create»"
BuyBookCommand                     -[#008200,dashed]-^  Command                           
BuyBookCommand                    "1" *-[#595959,plain]-> "selectedBook\n1" Knjiga                            
BuyBookCommand                    "1" *-[#595959,plain]-> "libraryManager\n1" LibraryManagerInterface           
BuyBookWindow                      -[#595959,dashed]->  BuyBookCommand                    : "«create»"
BuyBookWindow                      -[#595959,dashed]->  CardPayment                       : "«create»"
BuyBookWindow                      -[#595959,dashed]->  CashPayment                       : "«create»"
BuyBookWindow                      -[#595959,dashed]->  CryptoPayment                     : "«create»"
BuyBookWindow                      -[#595959,dashed]->  KnjigeViewPanel                   : "«create»"
BuyBookWindow                     "1" *-[#595959,plain]-> "knjigeViewPanel\n1" KnjigeViewPanel                   
BuyBookWindow                     "1" *-[#595959,plain]-> "paymentStrategy\n1" PaymentStrategy                   
BuyBookWindow                      -[#000082,plain]-^  ShortcuttableDialog               
CardPayment                        -[#008200,dashed]-^  PaymentStrategy                   
CashPayment                        -[#008200,dashed]-^  PaymentStrategy                   
CityMissingDecorator               -[#000082,plain]-^  MessageDecorator                  
CommandManager                     -[#008200,dashed]-^  CommandManagerInterface           
ConjoinedPanel                    "1" *-[#595959,plain]-> "listener\n1" ActionCommandListener             
ConjoinedPanel                     -[#000082,plain]-^  ActiveBasePanel                   
ConjoinedPanel                     -[#595959,dashed]->  CustomerViewPanel                 : "«create»"
ConjoinedPanel                    "1" *-[#595959,plain]-> "customerViewPanel\n1" CustomerViewPanel                 
ConjoinedPanel                     -[#595959,dashed]->  RegisterCustomerBottomPanel       : "«create»"
ConjoinedPanel                    "1" *-[#595959,plain]-> "registerCustomerBottomPanel\n1" RegisterCustomerBottomPanel       
ConjoinedPanel                    "1" *-[#595959,plain]-> "viewPanelListener\n1" ViewPanelListener                 
ConjoinedRegisterLibrarianPanel    -[#000082,plain]-^  BasePanel                         
ConjoinedRegisterLibrarianPanel    -[#595959,dashed]->  LibrarianViewPanel                : "«create»"
ConjoinedRegisterLibrarianPanel   "1" *-[#595959,plain]-> "librarianSearchField\n1" SearchField                       
ConjoinedRegisterLibrarianPanel    -[#595959,dashed]->  SearchField                       : "«create»"
ConjoinedRegisterLibrarianPanel   "1" *-[#595959,plain]-> "librarianViewPanel\n1" ViewPanel                         
CryptoPayment                      -[#008200,dashed]-^  PaymentStrategy                   
Customer                          "1" *-[#595959,plain]-> "posudeneKnjige\n*" Knjiga                            
Customer                           -[#000082,plain]-^  User                              
CustomerDAO                        -[#008200,dashed]-^  IntCustomerDAO                    
CustomerDAO                       "1" *-[#595959,plain]-> "customerFactory\n1" UserFactory                       
CustomerFactory                    -[#595959,dashed]->  Customer                          : "«create»"
CustomerFactory                    -[#008200,dashed]-^  UserFactory                       
CustomerHasBorrowedBooksDecorator  -[#000082,plain]-^  MessageDecorator                  
CustomerNotSelected                -[#000082,plain]-^  MessageDecorator                  
CustomerNotSelectedDecorator       -[#000082,plain]-^  MessageDecorator                  
CustomerViewPanel                  -[#000082,plain]-^  ViewPanel                         
DamageFeeDecorator                 -[#000082,plain]-^  MessageDecorator                  
DatabaseConnectionManager          -[#008200,dashed]-^  DBConnectionManagerInterface      
DeleteBookCommand                  -[#000082,plain]-^  BaseCommand                       
DeleteBookCommand                  -[#595959,dashed]->  BasicReturnMessage                : "«create»"
DeleteBookCommand                  -[#595959,dashed]->  BookAlreadyBorrowedDecorator      : "«create»"
DeleteBookCommand                  -[#595959,dashed]->  BookNotSelectedDecorator          : "«create»"
DeleteBookCommand                  -[#008200,dashed]-^  Command                           
DeleteBookCommand                 "1" *-[#595959,plain]-> "bookToDelete\n1" Knjiga                            
DeleteBookCommand                 "1" *-[#595959,plain]-> "libraryManager\n1" LibraryManagerInterface           
DeleteCustomerCommand              -[#000082,plain]-^  BaseCommand                       
DeleteCustomerCommand              -[#595959,dashed]->  BasicReturnMessage                : "«create»"
DeleteCustomerCommand              -[#008200,dashed]-^  Command                           
DeleteCustomerCommand             "1" *-[#595959,plain]-> "customer\n1" Customer                          
DeleteCustomerCommand              -[#595959,dashed]->  CustomerHasBorrowedBooksDecorator : "«create»"
DeleteCustomerCommand              -[#595959,dashed]->  CustomerNotSelected               : "«create»"
DeleteCustomerCommand             "1" *-[#595959,plain]-> "libraryManager\n1" LibraryManagerInterface           
DeleteLibrarianCommand             -[#000082,plain]-^  BaseCommand                       
DeleteLibrarianCommand             -[#595959,dashed]->  BasicReturnMessage                : "«create»"
DeleteLibrarianCommand             -[#008200,dashed]-^  Command                           
DeleteLibrarianCommand            "1" *-[#595959,plain]-> "librarian\n1" Librarian                         
DeleteLibrarianCommand             -[#595959,dashed]->  LibrarianLoggedInDecorator        : "«create»"
DeleteLibrarianCommand             -[#595959,dashed]->  LibrarianNotSelectedDecorator     : "«create»"
DeleteLibrarianCommand            "1" *-[#595959,plain]-> "libraryManager\n1" LibraryManagerInterface           
DeleteLibrarianCommand            "1" *-[#595959,plain]-> "sessionManager\n1" SessionManagerInterface           
EmptyAuthorDecorator               -[#000082,plain]-^  MessageDecorator                  
EmptyCijenaDecorator               -[#000082,plain]-^  MessageDecorator                  
EmptyISBNdecorator                 -[#000082,plain]-^  MessageDecorator                  
EmptyNazivDecorator                -[#000082,plain]-^  MessageDecorator                  
EmptyVrstaDecorator                -[#000082,plain]-^  MessageDecorator                  
Holder                             +-[#820000,plain]-  BookDAO                           
Holder                             -[#595959,dashed]->  BookDAO                           : "«create»"
Holder                            "1" *-[#595959,plain]-> "INSTANCE\n1" BookDAO                           
Holder                             +-[#820000,plain]-  CommandManager                    
Holder                            "1" *-[#595959,plain]-> "INSTANCE\n1" CommandManager                    
Holder                             -[#595959,dashed]->  CommandManager                    : "«create»"
Holder                             +-[#820000,plain]-  CustomerDAO                       
Holder                             -[#595959,dashed]->  CustomerDAO                       : "«create»"
Holder                            "1" *-[#595959,plain]-> "INSTANCE\n1" CustomerDAO                       
Holder                             +-[#820000,plain]-  DatabaseConnectionManager         
Holder                             -[#595959,dashed]->  DatabaseConnectionManager         : "«create»"
Holder                            "1" *-[#595959,plain]-> "INSTANCE\n1" DatabaseConnectionManager         
Holder                             +-[#820000,plain]-  LibrarianDAO                      
Holder                             -[#595959,dashed]->  LibrarianDAO                      : "«create»"
Holder                            "1" *-[#595959,plain]-> "INSTANCE\n1" LibrarianDAO                      
Holder                             +-[#820000,plain]-  LibraryManager                    
Holder                            "1" *-[#595959,plain]-> "INSTANCE\n1" LibraryManager                    
Holder                             -[#595959,dashed]->  LibraryManager                    : "«create»"
Holder                             +-[#820000,plain]-  SessionManager                    
Holder                             -[#595959,dashed]->  SessionManager                    : "«create»"
Holder                            "1" *-[#595959,plain]-> "INSTANCE\n1" SessionManager                    
InvalidAgeDecorator                -[#000082,plain]-^  MessageDecorator                  
Knjiga                            "1" *-[#595959,plain]-> "posudioCustomer\n1" Customer                          
KnjigeViewPanel                    -[#000082,plain]-^  ViewPanel                         
LastnameMissingDecorator           -[#000082,plain]-^  MessageDecorator                  
LateFeeDecorator                   -[#000082,plain]-^  MessageDecorator                  
Librarian                          -[#000082,plain]-^  User                              
LibrarianDAO                       -[#008200,dashed]-^  IntLibrarianDAO                   
LibrarianDAO                       -[#595959,dashed]->  Librarian                         : "«create»"
LibrarianFactory                   -[#595959,dashed]->  Librarian                         : "«create»"
LibrarianFactory                   -[#008200,dashed]-^  UserFactory                       
LibrarianLoggedInDecorator         -[#000082,plain]-^  MessageDecorator                  
LibrarianManagementPanel          "1" *-[#595959,plain]-> "listener\n1" ActionCommandListener             
LibrarianManagementPanel           -[#000082,plain]-^  ActiveBasePanel                   
LibrarianManagementWindow          -[#595959,dashed]->  DeleteLibrarianCommand            : "«create»"
LibrarianManagementWindow          -[#595959,dashed]->  LibrarianManagementPanel          : "«create»"
LibrarianManagementWindow         "1" *-[#595959,plain]-> "librarianManagementPanel\n1" LibrarianManagementPanel          
LibrarianManagementWindow         "1" *-[#595959,plain]-> "librarianViewPanel\n1" LibrarianViewPanel                
LibrarianManagementWindow          -[#595959,dashed]->  LibrarianViewPanel                : "«create»"
LibrarianManagementWindow          -[#595959,dashed]->  RegisterLibrarianWindow           : "«create»"
LibrarianManagementWindow         "1" *-[#595959,plain]-> "searchField\n1" SearchField                       
LibrarianManagementWindow          -[#595959,dashed]->  SearchField                       : "«create»"
LibrarianManagementWindow          -[#000082,plain]-^  ShortcuttableDialog               
LibrarianNotSelectedDecorator      -[#000082,plain]-^  MessageDecorator                  
LibrarianViewPanel                 -[#000082,plain]-^  ViewPanel                         
LibraryManager                    "1" *-[#595959,plain]-> "customers\n*" Customer                          
LibraryManager                    "1" *-[#595959,plain]-> "bDao\n1" IntBookDAO                        
LibraryManager                    "1" *-[#595959,plain]-> "cDao\n1" IntCustomerDAO                    
LibraryManager                    "1" *-[#595959,plain]-> "lDao\n1" IntLibrarianDAO                   
LibraryManager                    "1" *-[#595959,plain]-> "knjige\n*" Knjiga                            
LibraryManager                    "1" *-[#595959,plain]-> "librarians\n*" Librarian                         
LibraryManager                     -[#008200,dashed]-^  LibraryManagerInterface           
LibraryManager                    "1" *-[#595959,plain]-> "observers\n*" Observer                          
LibraryManagerInterface            -[#008200,plain]-^  FilterInterface                   
LibraryManagerInterface            -[#008200,plain]-^  Observable                        
LogInWindow                        -[#000082,plain]-^  BaseFrame                         
LogInWindow                        -[#595959,dashed]->  MainFrame                         : "«create»"
LogInWindow                        -[#595959,dashed]->  RegisterLibrarianWindow           : "«create»"
MainFrame                          -[#595959,dashed]->  AddBookWindow                     : "«create»"
MainFrame                          -[#595959,dashed]->  BorrowBookCommand                 : "«create»"
MainFrame                          -[#595959,dashed]->  BuyBookWindow                     : "«create»"
MainFrame                          -[#595959,dashed]->  KnjigeViewPanel                   : "«create»"
MainFrame                         "1" *-[#595959,plain]-> "knjigeViewPanel\n1" KnjigeViewPanel                   
MainFrame                          -[#595959,dashed]->  LibrarianManagementWindow         : "«create»"
MainFrame                          -[#595959,dashed]->  LogInWindow                       : "«create»"
MainFrame                          -[#595959,dashed]->  MainFrameFormPanel                : "«create»"
MainFrame                         "1" *-[#595959,plain]-> "formPanel\n1" MainFrameFormPanel                
MainFrame                         "1" *-[#595959,plain]-> "menuBar\n1" MenuBar                           
MainFrame                          -[#595959,dashed]->  MenuBar                           : "«create»"
MainFrame                          -[#595959,dashed]->  RegisterCustomerWindow            : "«create»"
MainFrame                          -[#595959,dashed]->  ReturnBookWindow                  : "«create»"
MainFrame                          -[#000082,plain]-^  ShortcuttableFrame                
MainFrame                          -[#595959,dashed]->  ToolBar                           : "«create»"
MainFrame                         "1" *-[#595959,plain]-> "toolBar\n1" ToolBar                           
MainFrameFormPanel                "1" *-[#595959,plain]-> "formPanelListener\n1" ActionCommandListener             
MainFrameFormPanel                 -[#000082,plain]-^  ActiveBasePanel                   
MainFrameFormPanel                "1" *-[#595959,plain]-> "customerViewPanel\n1" CustomerViewPanel                 
MainFrameFormPanel                 -[#595959,dashed]->  CustomerViewPanel                 : "«create»"
MainFrameFormPanel                "1" *-[#595959,plain]-> "bookSearchField\n1" SearchField                       
MainFrameFormPanel                 -[#595959,dashed]->  SearchField                       : "«create»"
MenuBar                           "1" *-[#595959,plain]-> "menuListener\n1" ActionCommandListener             
MessageDecorator                   -[#008200,dashed]-^  ReturnMessage                     
MessageDecorator                  "1" *-[#595959,plain]-> "decoratedMessage\n1" ReturnMessage                     
NameMissingDecorator               -[#000082,plain]-^  MessageDecorator                  
PasswordMissingDecorator           -[#000082,plain]-^  MessageDecorator                  
RegisterCustomerBottomPanel       "1" *-[#595959,plain]-> "listener\n1" ActionCommandListener             
RegisterCustomerBottomPanel        -[#000082,plain]-^  ActiveBasePanel                   
RegisterCustomerBottomPanel        -[#595959,dashed]->  SearchField                       : "«create»"
RegisterCustomerBottomPanel       "1" *-[#595959,plain]-> "customerSearchField\n1" SearchField                       
RegisterCustomerCommand            -[#595959,dashed]->  AddressMissingDecorator           : "«create»"
RegisterCustomerCommand            -[#000082,plain]-^  BaseCommand                       
RegisterCustomerCommand            -[#595959,dashed]->  BasicReturnMessage                : "«create»"
RegisterCustomerCommand            -[#595959,dashed]->  CityMissingDecorator              : "«create»"
RegisterCustomerCommand            -[#008200,dashed]-^  Command                           
RegisterCustomerCommand           "1" *-[#595959,plain]-> "newlyCreatedCustomer\n1" Customer                          
RegisterCustomerCommand            -[#595959,dashed]->  InvalidAgeDecorator               : "«create»"
RegisterCustomerCommand            -[#595959,dashed]->  LastnameMissingDecorator          : "«create»"
RegisterCustomerCommand           "1" *-[#595959,plain]-> "libraryManager\n1" LibraryManagerInterface           
RegisterCustomerCommand            -[#595959,dashed]->  NameMissingDecorator              : "«create»"
RegisterCustomerCommand           "1" *-[#595959,plain]-> "customerFactory\n1" UserFactory                       
RegisterCustomerPanel             "1" *-[#595959,plain]-> "listener\n1" ActionCommandListener             
RegisterCustomerPanel              -[#000082,plain]-^  ActiveBasePanel                   
RegisterCustomerWindow             -[#595959,dashed]->  ConjoinedPanel                    : "«create»"
RegisterCustomerWindow            "1" *-[#595959,plain]-> "conjoinedPanel\n1" ConjoinedPanel                    
RegisterCustomerWindow            "1" *-[#595959,plain]-> "selectedCustomer\n1" Customer                          
RegisterCustomerWindow             -[#595959,dashed]->  DeleteCustomerCommand             : "«create»"
RegisterCustomerWindow            "1" *-[#595959,plain]-> "knjigeViewPanel\n1" KnjigeViewPanel                   
RegisterCustomerWindow             -[#595959,dashed]->  KnjigeViewPanel                   : "«create»"
RegisterCustomerWindow             -[#595959,dashed]->  MainFrame                         : "«create»"
RegisterCustomerWindow             -[#595959,dashed]->  RegisterCustomerCommand           : "«create»"
RegisterCustomerWindow            "1" *-[#595959,plain]-> "registerCustomerPanel\n1" RegisterCustomerPanel             
RegisterCustomerWindow             -[#595959,dashed]->  RegisterCustomerPanel             : "«create»"
RegisterCustomerWindow             -[#000082,plain]-^  ShortcuttableFrame                
RegisterLibLeftPanel              "1" *-[#595959,plain]-> "libLeftPanelListener\n1" ActionCommandListener             
RegisterLibLeftPanel               -[#000082,plain]-^  ActiveBasePanel                   
RegisterLibrarianCommand           -[#595959,dashed]->  AddressMissingDecorator           : "«create»"
RegisterLibrarianCommand           -[#000082,plain]-^  BaseCommand                       
RegisterLibrarianCommand           -[#595959,dashed]->  BasicReturnMessage                : "«create»"
RegisterLibrarianCommand           -[#595959,dashed]->  CityMissingDecorator              : "«create»"
RegisterLibrarianCommand           -[#008200,dashed]-^  Command                           
RegisterLibrarianCommand           -[#595959,dashed]->  InvalidAgeDecorator               : "«create»"
RegisterLibrarianCommand           -[#595959,dashed]->  LastnameMissingDecorator          : "«create»"
RegisterLibrarianCommand          "1" *-[#595959,plain]-> "librarian\n1" Librarian                         
RegisterLibrarianCommand          "1" *-[#595959,plain]-> "librarianFactory\n1" LibrarianFactory                  
RegisterLibrarianCommand          "1" *-[#595959,plain]-> "libraryManager\n1" LibraryManagerInterface           
RegisterLibrarianCommand           -[#595959,dashed]->  NameMissingDecorator              : "«create»"
RegisterLibrarianCommand           -[#595959,dashed]->  PasswordMissingDecorator          : "«create»"
RegisterLibrarianCommand           -[#595959,dashed]->  UsernameMissingDecorator          : "«create»"
RegisterLibrarianWindow            -[#595959,dashed]->  ConjoinedRegisterLibrarianPanel   : "«create»"
RegisterLibrarianWindow           "1" *-[#595959,plain]-> "conjoinedPanel\n1" ConjoinedRegisterLibrarianPanel   
RegisterLibrarianWindow            -[#595959,dashed]->  RegisterLibLeftPanel              : "«create»"
RegisterLibrarianWindow           "1" *-[#595959,plain]-> "registerLibLeftPanel\n1" RegisterLibLeftPanel              
RegisterLibrarianWindow            -[#595959,dashed]->  RegisterLibrarianCommand          : "«create»"
RegisterLibrarianWindow            -[#000082,plain]-^  ShortcuttableDialog               
ReturnBookCommand                  -[#000082,plain]-^  BaseCommand                       
ReturnBookCommand                  -[#595959,dashed]->  BasicReturnMessage                : "«create»"
ReturnBookCommand                  -[#595959,dashed]->  BookNotBorrowedDecorator          : "«create»"
ReturnBookCommand                  -[#595959,dashed]->  BookNotSelectedDecorator          : "«create»"
ReturnBookCommand                  -[#008200,dashed]-^  Command                           
ReturnBookCommand                 "1" *-[#595959,plain]-> "customer\n1" Customer                          
ReturnBookCommand                  -[#595959,dashed]->  DamageFeeDecorator                : "«create»"
ReturnBookCommand                 "1" *-[#595959,plain]-> "selectedBook\n1" Knjiga                            
ReturnBookCommand                  -[#595959,dashed]->  LateFeeDecorator                  : "«create»"
ReturnBookCommand                 "1" *-[#595959,plain]-> "libraryManager\n1" LibraryManagerInterface           
ReturnBookFormPanel                -[#000082,plain]-^  ActiveBasePanel                   
ReturnBookFormPanel               "1" *-[#595959,plain]-> "returnBookFormListener\n1" ReturnBookFormListener            
ReturnBookWindow                   -[#595959,dashed]->  KnjigeViewPanel                   : "«create»"
ReturnBookWindow                   -[#595959,dashed]->  MainFrame                         : "«create»"
ReturnBookWindow                   -[#595959,dashed]->  ReturnBookCommand                 : "«create»"
ReturnBookWindow                  "1" *-[#595959,plain]-> "returnBookFormPanel\n1" ReturnBookFormPanel               
ReturnBookWindow                   -[#595959,dashed]->  ReturnBookFormPanel               : "«create»"
ReturnBookWindow                   -[#000082,plain]-^  ShortcuttableFrame                
ReturnBookWindow                  "1" *-[#595959,plain]-> "knjigeViewPanel\n1" ViewPanel                         
SearchField                       "1" *-[#595959,plain]-> "filePathEnum\n1" FilePathEnum                      
SessionManager                    "1" *-[#595959,plain]-> "loggedInUser\n1" Librarian                         
SessionManager                     -[#008200,dashed]-^  SessionManagerInterface           
ShortcuttableDialog                -[#000082,plain]-^  BaseDialog                        
ShortcuttableFrame                 -[#000082,plain]-^  BaseFrame                         
ToolBar                           "1" *-[#595959,plain]-> "toolBarListener\n1" ActionCommandListener             
ToolBar                            -[#000082,plain]-^  ActiveBasePanel                   
UsernameMissingDecorator           -[#000082,plain]-^  MessageDecorator                  
ViewPanel                          -[#000082,plain]-^  BasePanel                         
ViewPanel                         "1" *-[#595959,plain]-> "filePathEnum\n1" FilePathEnum                      
ViewPanel                          -[#008200,dashed]-^  Observer                          
ViewPanel                         "1" *-[#595959,plain]-> "listener\n1" ViewPanelListener                 
@enduml
